project_name: image-sync

before:
  hooks:
    - go mod tidy

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

archives:
  replacements:
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip