project_name: image-sync

before:
  hooks:
    - go mod tidy

builds:
  - id: autobrr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

archives:
  - id: autobrr
    builds:
      - autobrr
    replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip