name: Go

on:
  release:
    types: [created] # 表示在创建新的 Release 时触发

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
          cache: true
      - name: Build
        run: go build -v ./...
        # 使用 goreleaser 进行生成多平台代码并且上传到github release进行发布
      - name: Create release on GitHub
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}