name: huawei-image-sync

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'run action reason'
        required: false
        type: string
        default: 'manually test'
  schedule:
    - cron: '* */8 * * *'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  google-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Image Sync
        uses: cnsync/image-sync@v1.0.0
        env:
          DEST_REPO: "swr.cn-east-3.myhuaweicloud.com"
          HUB: "huawei"
          DEST_TRANSPORT_USER: "${{ secrets.HUAWEI_USER }}"
          DEST_TRANSPORT_PASSWORD: "${{ secrets.HUAWEI_PASSWORD }}"